version: '3'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: '${WEBSITE_IMAGE}'
    ports:
      - "3000:3000"
    volumes:
      - website:./website/build/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - website:/usr/share/nginx/html/website

volumes:
  website: