version: "3"
services:
  website:
    container_name: website
    image: 'ghcr.io/mathalro/matheusrosa-website/website:latest'
    hostname: website
    working_dir: /usr/src/app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    command: npm start

  api:
    container_name: api
    image: 'ghcr.io/mathalro/matheusrosa-website/api:latest'
    hostname: api
    networks:
      - node-network
    ports:
      - "8000:8000"
    command: npm run dev

  nginx:
    container_name: nginx
    image: 'ghcr.io/mathalro/matheusrosa-website/nginx:latest'
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - api
      - website

networks:
  node-network:
    driver: bridge