version: "3"
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    volumes:
      - website:/website/build/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - website:/usr/share/nginx/html/website

volumes:
  website:
